export const NotificationActions = {
 VOTATION_CREATED : "VOTATION_CREATED",
 RECEIVED_INVITATION_VOTATION : "RECEIVED_INVITATION_VOTATION",
 SEND_INVITATION_VOTATION : "SEND_INVITATION_VOTATION",
 TRANSFER_PROPERTY : "TRANSFER_PROPERTY",
 RECEIVED_PROPERTY : "RECEIVED_PROPERTY",
 INVITATION_REVOKED: "INVITATION_REVOKED",  // ← Agregado
 VOTATION_CLOSED : "VOTATION_CLOSED",

 
}